package com.enremmeta.rtb.constants;

import java.util.HashMap;
import java.util.Map;

/**
 * Categories per IAB
 * 
 * @see <a href="http://www.iab.net/">IAB</a>
 *
 * @author Gregory Golberg (grisha@alum.mit.edu)
 * 
 *         Copyright © <a href="http://www.enremmeta.com">Enremmeta LLC</a> 2014. All Rights
 *         Reserved. 
 *
 */
public class IABCategories {
    private static final Map<String, String> CATEGORIES_IAB = new HashMap<String, String>();

    public static final Map<String, String> IAB_CATEGORIES = new HashMap<String, String>() {
        {
            put("IAB_1", "Arts & Entertainment");
            put("IAB_1_1", "Books & Literature");
            put("IAB_1_2", "Celebrity Fan/Gossip");
            put("IAB_1_3", "Fine Art");
            put("IAB_1_4", "Humor");
            put("IAB_1_5", "Movies");
            put("IAB_1_6", "Music");
            put("IAB_1_7", "Television");
            put("IAB_2", "Automotive");
            put("IAB_2_1", "Auto Parts");
            put("IAB_2_2", "Auto Repair");
            put("IAB_2_3", "Buying/Selling Cars");
            put("IAB_2_4", "Car Culture");
            put("IAB_2_5", "Certified Pre_Owned");
            put("IAB_2_6", "Convertible");
            put("IAB_2_7", "Coupe");
            put("IAB_2_8", "Crossover");
            put("IAB_2_9", "Diesel");
            put("IAB_2_10", "Electric Vehicle");
            put("IAB_2_11", "Hatchback");
            put("IAB_2_12", "Hybrid");
            put("IAB_2_13", "Luxury");
            put("IAB_2_14", "MiniVan");
            put("IAB_2_15", "Mororcycles");
            put("IAB_2_16", "Off_Road Vehicles");
            put("IAB_2_17", "Performance Vehicles");
            put("IAB_2_18", "Pickup");
            put("IAB_2_19", "Road_Side Assistance");
            put("IAB_2_20", "Sedan");
            put("IAB_2_21", "Trucks & Accessories");
            put("IAB_2_22", "Vintage Cars");
            put("IAB_2_23", "Wagon");
            put("IAB_3", "Business");
            put("IAB_3_1", "Advertising");
            put("IAB_3_2", "Agriculture");
            put("IAB_3_3", "Biotech/Biomedical");
            put("IAB_3_4", "Business Software");
            put("IAB_3_5", "Construction");
            put("IAB_3_6", "Forestry");
            put("IAB_3_7", "Government");
            put("IAB_3_8", "Green Solutions");
            put("IAB_3_9", "Human Resources");
            put("IAB_3_10", "Logistics");
            put("IAB_3_11", "Marketing");
            put("IAB_3_12", "Metals");
            put("IAB_4", "Careers");
            put("IAB_4_1", "Career Planning");
            put("IAB_4_2", "College");
            put("IAB_4_3", "Financial Aid");
            put("IAB_4_4", "Job Fairsx");

            put("IAB_4_5", "Job Search");
            put("IAB_4_6", "Resume Writing/Advice");
            put("IAB_4_7", "Nursing");
            put("IAB_4_8", "Scholarships");
            put("IAB_4_9", "Telecommuting");
            put("IAB_4_10", "U.S. Military");
            put("IAB_4_11", "Career Advice");
            put("IAB_5", "Education");
            put("IAB_5_1", "7_12 Education");
            put("IAB_5_2", "Adult Education");
            put("IAB_5_3", "Art History");
            put("IAB_5_4", "Colledge Administration");
            put("IAB_5_5", "College Life");
            put("IAB_5_6", "Distance Learning");
            put("IAB_5_7", "English as a 2nd Language");
            put("IAB_5_8", "Language Learning");
            put("IAB_5_9", "Graduate School");
            put("IAB_5_10", "Homeschooling");
            put("IAB_5_11", "Homework/Study Tips");
            put("IAB_5_12", "K_6 Educators");
            put("IAB_5_13", "Private School");
            put("IAB_5_14", "Special Education");
            put("IAB_5_15", "Studying Business");
            put("IAB_6", "Family & Parenting");
            put("IAB_6_1", "Adoption");
            put("IAB_6_2", "Babies & Toddlers");
            put("IAB_6_3", "Daycare/Pre School");
            put("IAB_6_4", "Family Internet");
            put("IAB_6_5", "Parenting _ K_6 Kids");
            put("IAB_6_6", "Parenting teens");
            put("IAB_6_7", "Pregnancy");
            put("IAB_6_8", "Special Needs Kids");

            put("IAB_6_9", "Eldercare");
            put("IAB_7", "Health & Fitness");
            put("IAB_7_1", "Exercise");
            put("IAB_7_2", "A.D.D.");
            put("IAB_7_3", "AIDS/HIV");
            put("IAB_7_4", "Allergies");
            put("IAB_7_5", "Alternative Medicine");
            put("IAB_7_6", "Arthritis");
            put("IAB_7_7", "Asthma");
            put("IAB_7_8", "Autism/PDD");
            put("IAB_7_9", "Bipolar Disorder");
            put("IAB_7_10", "Brain Tumor");
            put("IAB_7_11", "Cancer");
            put("IAB_7_12", "Cholesterol");
            put("IAB_7_13", "Chronic Fatigue Syndrome");
            put("IAB_7_14", "Chronic Pain");
            put("IAB_7_15", "Cold & Flu");
            put("IAB_7_16", "Deafness");
            put("IAB_7_17", "Dental Care");
            put("IAB_7_18", "Depression");
            put("IAB_7_19", "Dermatology");
            put("IAB_7_20", "DIAB_etes");
            put("IAB_7_21", "Epilepsy");
            put("IAB_7_22", " GERD/Acid Reflux");
            put("IAB_7_23", " Headaches/Migraines");
            put("IAB_7_24", " Heart Disease");
            put("IAB_7_25", "Herbs for Health");
            put("IAB_7_26", " Holistic Healing");
            put("IAB_7_27", " IBS/Crohn's Disease");
            put("IAB_7_28", " Incest/Abuse Support");
            put("IAB_7_29", " Incontinence");
            put("IAB_7_30", "Infertility");
            put("IAB_7_31", "Men's Health");
            put("IAB_7_32", "Nutrition");
            put("IAB_7_33", "Orthopedics");
            put("IAB_7_34", "Panic/Anxiety Disorders");
            put("IAB_7_35", "Pediatrics");
            put("IAB_7_36", "Physical Therapy");
            put("IAB_7_37", "Psychology/Psychiatry");
            put("IAB_7_38", "Senor Health");
            put("IAB_7_39", "Sexuality");
            put("IAB_7_40", "Sleep Disorders");
            put("IAB_7_41", "Smoking Cessation");
            put("IAB_7_42", "Substance Abuse");
            put("IAB_7_43", "Thyroid Disease");
            put("IAB_7_44", "Weight Loss");
            put("IAB_7_45", "Women's Health");
            put("IAB_8", "Food & Drink");
            put("IAB_8_1", "American Cuisine");
            put("IAB_8_2", "Barbecues & Grilling");
            put("IAB_8_3", "Cajun/Creole");
            put("IAB_8_4", "Chinese Cuisine");
            put("IAB_8_5", "Cocktails/Beer");
            put("IAB_8_6", "Coffee/Tea");
            put("IAB_8_7", "Cuisine_Specific");
            put("IAB_8_8", "Desserts & Baking");
            put("IAB_8_9", "Dining Out");
            put("IAB_8_10", "Food Allergies");
            put("IAB_8_11", "French Cuisine");
            put("IAB_8_12", "Health/Lowfat Cooking");
            put("IAB_8_13", "Italian Cuisine");
            put("IAB_8_14", "Japanese Cuisine");
            put("IAB_8_15", "Mexican Cuisine");
            put("IAB_8_16", "Vegan");
            put("IAB_8_17", "Vegetarian");
            put("IAB_8_18", "Wine");
            put("IAB_9", "Hobbies & Interests");
            put("IAB_9_1", "Art/Technology");
            put("IAB_9_2", "Arts & Crafts");
            put("IAB_9_3", "Beadwork");
            put("IAB_9_4", "Birdwatching");
            put("IAB_9_5", "Board Games/Puzzles");
            put("IAB_9_6", "Candle & Soap Making");
            put("IAB_9_7", "Card Games");
            put("IAB_9_8", "Chess");
            put("IAB_9_9", "Cigars");
            put("IAB_9_10", "Collecting");
            put("IAB_9_11", "Comic Books");
            put("IAB_9_12", "Drawing/Sketching");
            put("IAB_9_13", "Freelance Writing");
            put("IAB_9_14", "Genealogy");
            put("IAB_9_15", "Getting Published");
            put("IAB_9_16", "Guitar");
            put("IAB_9_17", "Home Recording");
            put("IAB_9_18", "Investors & Patents");
            put("IAB_9_19", "Jewelry Making");
            put("IAB_9_20", "Magic & Illusion");
            put("IAB_9_21", "Needlework");
            put("IAB_9_22", "Painting");
            put("IAB_9_23", "Photography");
            put("IAB_9_24", "Radio");
            put("IAB_9_25", "Roleplaying Games");
            put("IAB_9_26", "Sci_Fi & Fantasy");
            put("IAB_9_27", "Scrapbooking");
            put("IAB_9_28", "Screenwriting");
            put("IAB_9_29", "Stamps & Coins");
            put("IAB_9_30", "Video & Computer Games");
            put("IAB_9_31", "Woodworking");
            put("IAB_10", "Home & Garden");
            put("IAB_10_1", "Appliances");
            put("IAB_10_2", "Entertaining");
            put("IAB_10_3", "Environmental Safety");
            put("IAB_10_4", "Gardening");
            put("IAB_10_5", "Home Repair");
            put("IAB_10_6", "Home Theater");
            put("IAB_10_7", "Interior Decorating");
            put("IAB_10_8", "Landscaping");
            put("IAB_10_9", "Remodeling & Construction");
            put("IAB_11", "Law, Gov't & Politics");
            put("IAB_11_1", "Immigration");
            put("IAB_11_2", "Legal Issues");
            put("IAB_11_3", "U.S. Government Resources");
            put("IAB_11_4", "Politics");
            put("IAB_11_5", "Commentary");
            put("IAB_12", "News");
            put("IAB_12_1", "International News");
            put("IAB_12_2", "National News");
            put("IAB_12_3", "Local News");
            put("IAB_13", "Personal Finance");
            put("IAB_13_1", "Beginning Investing");
            put("IAB_13_2", "Credit/Debt & Loans");
            put("IAB_13_3", "Financial News");
            put("IAB_13_4", "Financial Planning");
            put("IAB_13_5", "Hedge Fund");
            put("IAB_13_6", "Insurance");
            put("IAB_13_7", "Investing");
            put("IAB_13_8", "Mutual Funds");
            put("IAB_13_9", "Options");
            put("IAB_13_10", "Retirement Planning");
            put("IAB_13_11", "Stocks");
            put("IAB_13_12", "Tax Planning");
            put("IAB_14", "Society");
            put("IAB_14_1", "Dating");
            put("IAB_14_2", "Divorce Support");
            put("IAB_14_3", "Gay Life");
            put("IAB_14_4", "Marriage");
            put("IAB_14_5", "Senior Living");
            put("IAB_14_6", "Teens");
            put("IAB_14_7", "Weddings");
            put("IAB_14_8", "Ethnic Specific");
            put("IAB_15", "Science");
            put("IAB_15_1", "Astrology");
            put("IAB_15_2", "Biology");
            put("IAB_15_3", "Chemistry");
            put("IAB_15_4", "Geology");
            put("IAB_15_5", "Paranormal Phenomena");
            put("IAB_15_6", "Physics");
            put("IAB_15_7", "Space/Astronomy");
            put("IAB_15_8", "Geography");
            put("IAB_15_9", "Botany");
            put("IAB_15_10", "Weather");
            put("IAB_16", "Pets");
            put("IAB_16_1", "Aquariums");
            put("IAB_16_2", "Birds");
            put("IAB_16_3", "Cats");
            put("IAB_16_4", "Dogs");
            put("IAB_16_5", "Large Animals");
            put("IAB_16_6", "Reptiles");
            put("IAB_16_7", "Veterinary Medicine");
            put("IAB_17", "Sports");
            put("IAB_17_1", "Auto Racing");
            put("IAB_17_2", "Baseball");
            put("IAB_17_3", "Bicycling");
            put("IAB_17_4", "Bodybuilding");
            put("IAB_17_5", "Boxing");
            put("IAB_17_6", "Canoeing/Kayaking");
            put("IAB_17_7", "Cheerleading");
            put("IAB_17_8", "Climbing");
            put("IAB_17_9", "Cricket");
            put("IAB_17_10", "Figure Skating");
            put("IAB_17_11", "Fly Fishing");
            put("IAB_17_12", "Football");
            put("IAB_17_13", "Freshwater Fishing");
            put("IAB_17_14", "Game & Fish");
            put("IAB_17_15", "Golf");
            put("IAB_17_16", "Horse Racing");
            put("IAB_17_17", "Horses");
            put("IAB_17_18", "Hunting/Shooting");
            put("IAB_17_19", "Inline Skating");
            put("IAB_17_20", "Martial Arts");
            put("IAB_17_21", "Mountain Biking");
            put("IAB_17_22", "NASCAR Racing");
            put("IAB_17_23", "Olympics");
            put("IAB_17_24", "Paintball");
            put("IAB_17_25", "Power & Motorcycles");
            put("IAB_17_26", "Pro Basketball");
            put("IAB_17_27", "Pro Ice Hockey");
            put("IAB_17_28", "Rodeo");
            put("IAB_17_29", "Rugby");
            put("IAB_17_30", "Running/Jogging");
            put("IAB_17_31", "Sailing");
            put("IAB_17_32", "Saltwater Fishing");
            put("IAB_17_33", "Scuba Diving");
            put("IAB_17_34", "Skateboarding");
            put("IAB_17_35", "Skiing");
            put("IAB_17_36", "Snowboarding");
            put("IAB_17_37", "Surfing/Bodyboarding");
            put("IAB_17_38", "Swimming");
            put("IAB_17_39", "Table Tennis/Ping_Pong");
            put("IAB_17_40", "Tennis");
            put("IAB_17_41", "Volleyball");
            put("IAB_17_42", "Walking");
            put("IAB_17_43", "Waterski/Wakeboard");
            put("IAB_17_44", "World Soccer");
            put("IAB_18", "Style & Fashion");
            put("IAB_18_1", "Beauty");
            put("IAB_18_2", "Body Art");
            put("IAB_18_3", "Fashion");
            put("IAB_18_4", "Jewelry");
            put("IAB_18_5", "Clothing");
            put("IAB_18_6", "Accessories");
            put("IAB_19", "Technology & Computing");
            put("IAB_19_1", "3_D Graphics");
            put("IAB_19_2", "Animation");
            put("IAB_19_3", "Antivirus Software");
            put("IAB_19_4", "C/C++");
            put("IAB_19_5", "Cameras & Camcorders");
            put("IAB_19_6", "Cell Phones");
            put("IAB_19_7", "Computer Certification");
            put("IAB_19_8", "Computer Networking");
            put("IAB_19_9", "Computer Peripherals");
            put("IAB_19_10", "Computer Reviews");
            put("IAB_19_11", "Data Centers");
            put("IAB_19_12", "Databases");
            put("IAB_19_13", "Desktop Publishing");
            put("IAB_19_14", "Desktop Video");
            put("IAB_19_15", "Email");
            put("IAB_19_16", "Graphics Software");
            put("IAB_19_17", "Home Video/DVD");
            put("IAB_19_18", "Internet Technology");
            put("IAB_19_19", "Java");
            put("IAB_19_20", "JavaScript");
            put("IAB_19_21", "Mac Support");
            put("IAB_19_22", "MP3/MIDI");
            put("IAB_19_23", "Net Conferencing");
            put("IAB_19_24", "Net for Beginners");
            put("IAB_19_25", "Network Security");
            put("IAB_19_26", "Palmtops/PDAs");
            put("IAB_19_27", "PC Support");
            put("IAB_19_28", "Portable");
            put("IAB_19_29", "Entertainment");
            put("IAB_19_30", "Shareware/Freeware");
            put("IAB_19_31", "Unix");
            put("IAB_19_32", "Visual Basic");
            put("IAB_19_33", "Web Clip Art");
            put("IAB_19_34", "Web Design/HTML");
            put("IAB_19_35", "Web Search");
            put("IAB_19_36", "Windows");
            put("IAB_20", "Travel");
            put("IAB_20_1", "Adventure Travel");
            put("IAB_20_2", "Africa");
            put("IAB_20_3", "Air Travel");
            put("IAB_20_4", "Australia & New Zealand");
            put("IAB_20_5", "Bed & Breakfasts");
            put("IAB_20_6", "Budget Travel");
            put("IAB_20_7", "Business Travel");
            put("IAB_20_8", "By US Locale");
            put("IAB_20_9", "Camping");
            put("IAB_20_10", "Canada");
            put("IAB_20_11", "Caribbean");
            put("IAB_20_12", "Cruises");
            put("IAB_20_13", "Eastern Europe");
            put("IAB_20_14", "Europe");
            put("IAB_20_15", "France");
            put("IAB_20_16", "Greece");
            put("IAB_20_17", "Honeymoons/Getaways");
            put("IAB_20_18", "Hotels");
            put("IAB_20_19", "Italy");
            put("IAB_20_20", "Japan");
            put("IAB_20_21", "Mexico & Central America");
            put("IAB_20_22", "National Parks");
            put("IAB_20_23", "South America");
            put("IAB_20_24", "Spas");
            put("IAB_20_25", "Theme Parks");
            put("IAB_20_26", "Traveling with Kids");
            put("IAB_20_27", "United Kingdom");
            put("IAB_21", "Real Estate");
            put("IAB_21_1", "Apartments");
            put("IAB_21_2", "Architects");
            put("IAB_21_3", "Buying/Selling Homes");
            put("IAB_22", "Shopping");
            put("IAB_22_1", "Contests & Freebies");
            put("IAB_22_2", "Couponing");
            put("IAB_22_3", "Comparison");
            put("IAB_22_4", "Engines");
            put("IAB_23", "Religion & Spirituality");
            put("IAB_23_1", "Alternative Religions");
            put("IAB_23_2", " Atheism/Agnosticism");
            put("IAB_23_3", "Buddhism");
            put("IAB_23_4", "Catholicism");
            put("IAB_23_5", "Christianity");
            put("IAB_23_6", "Hinduism");
            put("IAB_23_7", "Islam");
            put("IAB_23_8", "Judaism");
            put("IAB_23_9", "Latter_Day Saints");
            put("IAB_23_10", "Pagan/Wiccan");
            put("IAB_24", "Uncategorized");
            put("IAB_25", "Non_Standard Content");
            put("IAB_25_1", "Unmoderated UGC");
            put("IAB_25_2", "Extreme Graphic/Explicit Violence");
            put("IAB_25_3", "Pornography");
            put("IAB_25_4", "Profane Content");
            put("IAB_25_5", "Hate Content");
            put("IAB_25_6", "Under Construction");
            put("IAB_25_7", "Incentivized");
            put("IAB_26", "Illegal Content");
            put("IAB_26_1", "Illegal Content");
            put("IAB_26_2", "Warez");
            put("IAB_26_3", "Spyware/Malware");
            put("IAB_26_4", "Copyright Infringement");
        }
    };

    public static final String getIabCategoryId(String cat) {
        if (CATEGORIES_IAB.size() == 0) {
            for (String iabCat : IAB_CATEGORIES.keySet()) {
                String catName = IAB_CATEGORIES.get(iabCat);
                CATEGORIES_IAB.put(catName, iabCat);
            }
        }
        return CATEGORIES_IAB.get(cat);
    }
}
